[
    {
        "message": "H1ESC",
        "model_trainer":{
            "class": "keras_model_trainer.KerasFitGeneratorModelTrainer",
            "kwargs": {
                "seed": 1234,
                "samples_per_epoch": 100,
                "stopping_criterion_config": {
                    "class": "EarlyStopping" ,
                    "kwargs": {
                       "max_epochs": 300,
                       "epochs_to_wait": 3
                    }
                },
                #"class_weight": {"0":1, "1":25}
            }
        },
        "model_creator":{
            "class": "flexible_keras.FlexibleKerasSequential",
            "kwargs": {
                    "layers_config": [
                    {
                        "class": "keras.layers.convolutional.Convolution1D",
                        "kwargs": {
                            "input_shape": [400,4],
                            "filter_length": 8,
                            "border_mode": "valid",
                            "nb_filter": 320,
                            "kernel_initializer": "he_normal"
                        }
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu"}
                    },
                    {
                        "class": "keras.layers.convolutional.Convolution1D",
                        "kwargs": {
                            "filter_length": 8,
                            "border_mode": "valid",
                            "nb_filter": 320,
                            "kernel_initializer": "he_normal"
                        }
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu"}
                    },
                    {
                        "class": "keras.layers.core.Dropout",
                        "kwargs": {"p": 0.2}
                    },
                    {
                        "class": "keras.layers.pooling.MaxPooling1D",
                        "kwargs": {
                            "border_mode": "valid",
                            "pool_length": 4,
                            "stride": 4
                        }
                    },
                    {
                        "class": "keras.layers.convolutional.Convolution1D",
                        "kwargs": {
                            "filter_length": 8,
                            "border_mode": "valid",
                            "nb_filter": 480,
                            "kernel_initializer": "he_normal"
                        }
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu"}
                    },
                    {
                        "class": "keras.layers.convolutional.Convolution1D",
                        "kwargs": {
                            "filter_length": 8,
                            "border_mode": "valid",
                            "nb_filter": 480,
                            "kernel_initializer": "he_normal"
                        }
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu"}
                    },
                    {
                        "class": "keras.layers.core.Dropout",
                        "kwargs": {"p": 0.2}
                    },
                    {
                        "class": "keras.layers.pooling.MaxPooling1D",
                        "kwargs": {
                            "border_mode": "valid",
                            "pool_length": 4,
                            "stride": 4
                        }
                    },
{
                        "class": "keras.layers.convolutional.Convolution1D",
                        "kwargs": {
                            "filter_length": 8,
                            "border_mode": "valid",
                            "nb_filter": 640,
                            "kernel_initializer": "he_normal"
                        }
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu"}
                    },
                    {
                        "class": "keras.layers.convolutional.Convolution1D",
                        "kwargs": {
                            "filter_length": 8,
                            "border_mode": "valid",
                            "nb_filter": 640,
                            "kernel_initializer": "he_normal"
                        }
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu"}
                    },
                    {
                        "class": "keras.layers.core.Dropout",
                        "kwargs": {"p": 0.5}
                    },
                    {
                        "class": "keras.layers.core.Flatten",
                        "kwargs": {}
                    },
                    {
                        "class": "keras.layers.core.Dense",
                        "kwargs": {"output_dim": 2000, "kernel_initializer": "he_normal"}
                    },
                    {
                        "class": "keras.layers.core.Activation",
                        "kwargs": {"activation": "relu"}
                     },
                    {
                        "class": "keras.layers.core.Dense",
                        "kwargs": {"output_dim": 1, "kernel_initializer": "he_normal"}
                    },
                    {
                        "class": "keras.layers.core.Activation",
                        "kwargs": {"activation": "sigmoid"}
                     }
            ],
                "optimizer_config": {
                    "class": "keras.optimizers.Adam",
                    "kwargs": {"lr": 0.0001}
                },
                "loss": "binary_crossentropy" 
            }
        },
        "other_data_loaders":{
            "train": {
                "class": "fasta_inmemory_data_loader.TwoStreamSeqOnly",
                "kwargs": {
                   "batch_size": 300,
                   "positives_fasta_source": "/users/eprakash/git/interpret-benchmark/data/dnase_positives/common_scripts/H1/sequences/train_sim_positives.txt.gz",
                   "negatives_fasta_source": "/users/eprakash/git/interpret-benchmark/data/dnase_positives/common_scripts/H1/sequences/train_sim_negatives.txt.gz",
                   "fasta_col": 1,
                   "negatives_to_positives_ratio": 1,
                   "rc_augment": true,
                   "num_to_load_for_eval": 5000, 
                   "labels_dtype": "int"
                }
            }
        },
    }
]
